# JWT
ACCESS_TOKEN_EXPIRE_MINUTES = 1
REFRESH_TOKEN_EXPIRE_MINUTES = 1
ALGORITHM = "encription algorithm"
JWT_SECRET_KEY = "secret key"
JWT_REFRESH_SECRET_KEY = "secret key"

# DETA
PROJECT_KEY = "project key"
